apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdde.fullname" . }}-cms
  labels:
    {{- include "cdde.labels" . | nindent 4 }}
    app.kubernetes.io/component: cms
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.cms.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cdde.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cms
