apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdde.fullname" . }}-dfl
  labels:
    {{- include "cdde.labels" . | nindent 4 }}
    app.kubernetes.io/component: dfl
spec:
  replicas: {{ .Values.dfl.replicaCount }}
  selector:
    matchLabels:
      {{- include "cdde.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dfl
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cdde.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dfl
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cdde.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: dfl
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./cdde-dfl"]
          env:
            - name: RUST_LOG
              value: "info"
            # Add other necessary environment variables here
          ports:
            - name: diameter
              containerPort: 3868
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
